// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcRghyFvpCil6k3NvNK_u2wp0UDuDydcU',
    appId: '1:1053773858698:web:af574425443d909eb22a73',
    messagingSenderId: '1053773858698',
    projectId: 'thikramuslimathkar',
    authDomain: 'thikramuslimathkar.firebaseapp.com',
    storageBucket: 'thikramuslimathkar.firebasestorage.app',
    measurementId: 'G-0XX0P2CNHR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvcE4XDR_bvtNCh51olmzJFVktOczC3Cc',
    appId: '1:1053773858698:android:27485e27a4e03e39b22a73',
    messagingSenderId: '1053773858698',
    projectId: 'thikramuslimathkar',
    storageBucket: 'thikramuslimathkar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC69tbwhWdTyzNRREUn5a5kLu6YYiF1iN0',
    appId: '1:1053773858698:ios:45c45c029bd9efd5b22a73',
    messagingSenderId: '1053773858698',
    projectId: 'thikramuslimathkar',
    storageBucket: 'thikramuslimathkar.firebasestorage.app',
    iosBundleId: 'com.example.app21days',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC69tbwhWdTyzNRREUn5a5kLu6YYiF1iN0',
    appId: '1:1053773858698:ios:45c45c029bd9efd5b22a73',
    messagingSenderId: '1053773858698',
    projectId: 'thikramuslimathkar',
    storageBucket: 'thikramuslimathkar.firebasestorage.app',
    iosBundleId: 'com.example.app21days',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcRghyFvpCil6k3NvNK_u2wp0UDuDydcU',
    appId: '1:1053773858698:web:7aba83f35c91c1f6b22a73',
    messagingSenderId: '1053773858698',
    projectId: 'thikramuslimathkar',
    authDomain: 'thikramuslimathkar.firebaseapp.com',
    storageBucket: 'thikramuslimathkar.firebasestorage.app',
    measurementId: 'G-JLYKQV6B6Z',
  );
}
